### ISSUE TITLE
Ruby Rvm install 2.3.1 - GEM_PATH

### ISSUE THREAD

**Issue by tilipim123** [markets/awesome-ruby#981]
When running rvm install "ruby-2.3.1" I got this error:

```
Error running 'env GEM_HOME=/Users/caiofelipe/.rvm/gems/ruby-2.3.1@global GEM_PATH= /Users/caiofelipe/.rvm/rubies/ruby-2.3.1/bin/ruby -d /Users/caiofelipe/.rvm/src/rubygems-3.0.8/setup.rb --no-document',
please read /Users/caiofelipe/.rvm/log/1584630897_ruby-2.3.1/rubygems.install.log
```

The log (rubygems.install.log) has this:
```
Exception `LoadError' at /Users/caiofelipe/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb:1241 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/caiofelipe/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /Users/caiofelipe/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
/Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- openssl (LoadError)
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/specification.rb:2481:in `to_ruby'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/commands/setup_command.rb:405:in `install_default_bundler_gem'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/commands/setup_command.rb:167:in `execute'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/command.rb:321:in `invoke_with_build_args'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/command_manager.rb:184:in `process_args'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/command_manager.rb:148:in `run'
    from /Users/caiofelipe/.rvm/src/rubygems-3.0.8/lib/rubygems/gem_runner.rb:59:in `run'
    from setup.rb:41:in `<main>'
```

**Comment by markets** [comment]
Sorry this is not related to the Awesome Ruby project, try in StackOverflow or maybe in the RVM repo.
